#!/bin/bash

# -----------------------------
# Configuration
# -----------------------------
PROJECT_FOLDER="$HOME/Echo"
SUGGESTIONS_FILE="ai_suggestions.txt"
LOG_FILE="progress_log.json"
BACKUP_FOLDER="backup_project"

# -----------------------------
# Backup Project
# -----------------------------
if [ ! -d "$BACKUP_FOLDER" ]; then
    cp -r "$PROJECT_FOLDER" "$BACKUP_FOLDER"
    echo "Backup created at $BACKUP_FOLDER"
fi

# -----------------------------
# Initialize Log
# -----------------------------
if [ ! -f "$LOG_FILE" ]; then
    echo "[]" > "$LOG_FILE"
fi

# -----------------------------
# Function: Apply Suggestion
# -----------------------------
apply_suggestion() {
    local suggestion="$1"
    local result=""

    # Create file
    if [[ "$suggestion" =~ ^[Cc]reate\ file\ (.+)$ ]]; then
        local filename="${BASH_REMATCH[1]}"
        local filepath="$PROJECT_FOLDER/$filename"
        if [ ! -f "$filepath" ]; then
            echo "# New module generated by Echo" > "$filepath"
            result="Created file $filename"
        else
            result="$filename already exists"
        fi

    # Add function
    elif [[ "$suggestion" =~ ^[Aa]dd\ function\ (.+)\ to\ file\ (.+)$ ]]; then
        local func_name="${BASH_REMATCH[1]}"
        local file_name="${BASH_REMATCH[2]}"
        local filepath="$PROJECT_FOLDER/$file_name"
        [ -f "$filepath" ] || echo "# New module generated by Echo" > "$filepath"
        echo -e "\n\ndef $func_name():\n    # TODO: Implement $func_name\n    pass" >> "$filepath"
        result="Added function $func_name to $file_name"

    # Refactor module
    elif [[ "$suggestion" =~ ^[Rr]efactor\ module\ (.+)$ ]]; then
        local module_name="${BASH_REMATCH[1]}"
        result="Refactor requested for module $module_name (manual review recommended)"

    else
        result="Suggestion not automated"
    fi

    # Escape control characters for JSON safety
    escaped_suggestion=$(echo "$suggestion" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')
    escaped_result=$(echo "$result" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')

    # Log single suggestion result
    echo "{\"suggestion\": $escaped_suggestion, \"result\": $escaped_result}" >> tmp_log.json
    echo "$result"
}

# -----------------------------
# Load Suggestions
# -----------------------------
mapfile -t suggestions < "$SUGGESTIONS_FILE"

# -----------------------------
# Apply Suggestions
# -----------------------------
rm -f tmp_log.json
for s in "${suggestions[@]}"; do
    apply_suggestion "$s"
done

# -----------------------------
# Merge tmp_log.json into LOG_FILE
# -----------------------------
if command -v jq &> /dev/null; then
    jq -s '.[0] + .[1]' <(cat "$LOG_FILE") <(cat tmp_log.json) > tmp_merged.json
    mv tmp_merged.json "$LOG_FILE"
else
    cat tmp_log.json >> "$LOG_FILE"
fi

# -----------------------------
# Run Tests
# -----------------------------
cd "$PROJECT_FOLDER"
if command -v pytest &> /dev/null; then
    TEST_OUTPUT=$(pytest --maxfail=1 --disable-warnings)
    TEST_STATUS=$?
    # Escape test output for JSON
    escaped_output=$(echo "$TEST_OUTPUT" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')
    echo "{\"tests\": {\"status\": \"$([ $TEST_STATUS -eq 0 ] && echo PASS || echo FAIL)\", \"output\": $escaped_output}}" >> "$LOG_FILE"
    echo "Test results logged."
else
    echo "{\"tests\": {\"status\": \"NOT FOUND\", \"output\": \"pytest not installed\"}}" >> "$LOG_FILE"
    echo "pytest not found, skipping tests."
fi

echo "Echo automation complete!"
