#!/bin/bash

# -----------------------------
# Configuration
# -----------------------------
#PROJECT_FOLDER="path/to/your/project"   # <-- replace with your project folder
PROJECT_FOLDER="$HOME/Echo"
SUGGESTIONS_FILE="ai_suggestions.txt"  # Tab 1 + Tab 2 outputs
LOG_FILE="progress_log.json"
BACKUP_FOLDER="backup_project"

# -----------------------------
# Backup Project
# -----------------------------
if [ ! -d "$BACKUP_FOLDER" ]; then
    cp -r "$PROJECT_FOLDER" "$BACKUP_FOLDER"
    echo "Backup created at $BACKUP_FOLDER"
fi

# -----------------------------
# Initialize Log
# -----------------------------
if [ ! -f "$LOG_FILE" ]; then
    echo "[]" > "$LOG_FILE"
fi

# -----------------------------
# Function: Apply Suggestion
# -----------------------------
apply_suggestion() {
    local suggestion="$1"
    echo "Applying suggestion: $suggestion"

    # Simple pattern: create file
    if [[ "$suggestion" =~ ^[Cc]reate\ file\ (.+)$ ]]; then
        local filename="${BASH_REMATCH[1]}"
        local filepath="$PROJECT_FOLDER/$filename"
        if [ ! -f "$filepath" ]; then
            echo "# New module generated by Echo" > "$filepath"
            echo "{\"suggestion\": \"$suggestion\", \"result\": \"Created $filename\"}" >> tmp_log.json
        else
            echo "{\"suggestion\": \"$suggestion\", \"result\": \"$filename already exists\"}" >> tmp_log.json
        fi
    else
        echo "{\"suggestion\": \"$suggestion\", \"result\": \"Not automated\"}" >> tmp_log.json
    fi
}

# -----------------------------
# Load Suggestions
# -----------------------------
mapfile -t suggestions < "$SUGGESTIONS_FILE"

# -----------------------------
# Apply Suggestions
# -----------------------------
rm -f tmp_log.json
for s in "${suggestions[@]}"; do
    apply_suggestion "$s"
done

# -----------------------------
# Merge tmp_log.json into LOG_FILE
# -----------------------------
jq -s '.[0] + .[1]' <(cat "$LOG_FILE") <(cat tmp_log.json) > tmp_merged.json
mv tmp_merged.json "$LOG_FILE"

# -----------------------------
# Run Tests
# -----------------------------
cd "$PROJECT_FOLDER"
if command -v pytest &> /dev/null; then
    TEST_OUTPUT=$(pytest --maxfail=1 --disable-warnings)
    TEST_STATUS=$?
    echo "{\"tests\": {\"status\": \"$([ $TEST_STATUS -eq 0 ] && echo PASS || echo FAIL)\", \"output\": \"$TEST_OUTPUT\"}}" >> "$LOG_FILE"
    echo "Test results logged."
else
    echo "{\"tests\": {\"status\": \"NOT FOUND\", \"output\": \"pytest not installed\"}}" >> "$LOG_FILE"
    echo "pytest not found, skipping tests."
fi

echo "Echo automation complete!"
